const NUM_X = 15;
const NUM_Y = 15;
const SQ_SIZE = 25;
const STARTING_FOODS = 30;
const FOOD_COLOR = "rgba(0, 255, 0, 0.3)";
const NUM_NEIGHBORS_THRESHOLD = 15;

export { NUM_X, NUM_Y, SQ_SIZE, STARTING_FOODS, FOOD_COLOR, NUM_NEIGHBORS_THRESHOLD };
